### ISSUE TITLE
[Feature] VideoPlayer and DownloadManager.

### ISSUE THREAD

**Issue by luffyiodas49** [zyrouge/yukino-app#17]
**Is your feature request related to a problem? Please describe.**
Add VideoPlayer and DownloadManager.

**Describe the solution you'd like**
It would be better to have a videopalyer, to watch and Download-manager to download, internally.

**Additional context**
Infuture The UI of the Yukino-app can be like this, with feature to watch, download, Accounts,C, my list, etc...

Home Page.
![Screenshot1](https://user-images.githubusercontent.com/45803655/121988638-547bad00-cdb8-11eb-90be-cbf45f43b1f9.png)

My Anime, My List, Favorite, etc..
![Screenshot2](https://user-images.githubusercontent.com/45803655/121989085-23e84300-cdb9-11eb-8c86-2982b8009fa6.png)

This Season, Schedule, etc...
![Screenshot3](https://user-images.githubusercontent.com/45803655/121989103-29458d80-cdb9-11eb-9486-620be9bcec04.png)

Genres, Search...
![Screenshot4](https://user-images.githubusercontent.com/45803655/121989122-2e0a4180-cdb9-11eb-81e9-a5eaca376290.png)

Schedule...
![Screenshot5](https://user-images.githubusercontent.com/45803655/121989132-32365f00-cdb9-11eb-8a55-1f2394e9ec76.png)

**Comment by zyrouge** [comment]
Certainly the UI suits for larger displays, it certainly won't be implemented considering other platforms such as mobile. The UI will stay as simple as possible yet attractive.

**Comment by luffyiodas49** [comment]
You can have different UI for different platforms.....such as mobile, desktop, etc. (I can give UI ideas for mobile too..). An attractive UI is the best.
