### ISSUE TITLE
[Feature] MacOS Support

### ISSUE THREAD

**Issue by thamognya** [zyrouge/yukino-app#178]
I would like to request a release for macOS as there are no such releases available. The release for Linux works well but I wish there were a release or download link for macOS and more preferably homebrew release to install it via the terminal like so: 
`brew install yukino` .

## Checklist

-   [x] I have read the [Contribution Guidelines](https://yukino-app.github.io/wiki/developers/contribution/#contribution).

**Comment by zyrouge** [comment]
Sadly I've mentioned it in a pinned issue (https://github.com/yukino-app/yukino/issues/138), I don't have a Mac inorder to test the app. Unless someone contributes, don't expect this to happen. Also the fact that the build fails and has pending changes to make the app working completely in MacOS.

**Comment by thamognya** [comment]
I will try and solve this using my mac during my free time and try to make a pr or issue discussing about this. Thank you for your quick response.
