### ISSUE TITLE
[Feature] Discord RPC Toggle

### ISSUE THREAD

**Issue by shadeoxide** [zyrouge/yukino-app#31]
**Is your feature request related to a problem? Please describe.**
Not exactly a problem, but this feature could be useful for people who don't want to show which anime they are watching.

**Describe the solution you'd like**
A simple toggle where you can select whether you want to show Yukino's Discord RPC

**Describe alternatives you've considered**
Alternative solution can be turning off "Show what I'm playing" setting in the Discord App, which doesn't show your RPC, but an in-built feature of Yukino App would be better.

**Additional context**
None

**Comment by zyrouge** [comment]
Already there i guess :')
![image](https://user-images.githubusercontent.com/50770114/122664101-de62b600-d1bc-11eb-9da3-93e348f1fa26.png)

**Comment by shadeoxide** [comment]
oops  sorry
