### ISSUE TITLE
[Bug] Area for moving the window

### ISSUE THREAD

**Issue by RandomClaim** [zyrouge/yukino-app#33]
**Describe the bug**
Moving the window does not work when dragging at the top bar, only when the cursor is on the app name/version number in the upper left.

**Expected behavior**
The window is movable from any position in the top bar.

**Screenshots**
![Screenshot 2021-06-21 101931](https://user-images.githubusercontent.com/9338392/122730163-37445400-d27a-11eb-995f-9698a968ee7b.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 0.0.20

**Mobile (please complete the following information):**
 - Device: [e.g. Pixel 5]
 - Version: [e.g. 22]

**Comment by zyrouge** [comment]
Fixed in 0.0.21-beta.0.
