### ISSUE TITLE
[Feature] In-App Minimize Media-Player

### ISSUE THREAD

**Issue by EhsanFox** [zyrouge/yukino-app#42]
**Is your feature request related to a problem? Please describe.**
Some people might want to search about another Anime While watching their show

**Describe the solution you'd like**
Having a Minimized In-App Media Player Would be Awsome instead of showing Continu Watching thing....

**Describe alternatives you've considered**
it might be delayed till the Custom Media Player Be Done.

**Additional context**
![image](https://user-images.githubusercontent.com/20506391/123052812-171aaf00-d3b8-11eb-91f5-e5d93147bfcb.png)

**Comment by zyrouge** [comment]
Not possible as the stream links expire time to time making it impossible to replay the same stream. Closing this as no possible solution exist.
