### ISSUE TITLE
[Feature] Manga Tracking

### ISSUE THREAD

**Issue by eXil3d** [zyrouge/yukino-app#58]
**Is your feature request related to a problem? Please describe.**
Add manga tracking for MAL and Anilist

**Describe the solution you'd like**
Include a manga tracking feature like anime tracking which would auto update the read chapters in MAL or Anilist

**Describe alternatives you've considered**
If not possible then what else to do except manually updating them

**Comment by eXil3d** [comment]
Also pls improve the manga reader

**Comment by zyrouge** [comment]
UI will see some necessary updates in the future after necessary things are done! :)
