### ISSUE TITLE
[Feature] Anilist connection sync

### ISSUE THREAD

**Issue by Laezor** [zyrouge/yukino-app#59]
Any possibility of adding Anilist as a connection to sync the anime or manga you are watching? Since I do not use MyAnimeList!

**Comment by eXil3d** [comment]
Zyrouge is currently working on Anilist sync. Don't worry I hope this would be added with the next update. Also to track the progress of this project keep an eye [here](https://github.com/zyrouge/yukino-app/projects/1)

**Comment by Laezor** [comment]
I see thank you, for the quick response!
