### ISSUE TITLE
[Bug] Anilist Profile says the last update was in 1970

### ISSUE THREAD

**Issue by xKings** [zyrouge/yukino-app#70]
**Describe the bug**
Whenever you press view on the Anilist connection, the last update is defaulted to 1970, even for recent anime.

**To Reproduce**
1. Go to 'Connections'
2. Click on 'View on your profile'
3. Scroll down to 'any anime and it says the last update is 1970.'

**Expected behavior**
It should say the last time a new episode was released. 

**Screenshots**
![image](https://user-images.githubusercontent.com/42078899/124523515-63f18300-ddc5-11eb-9491-ec160684f44d.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Version: [10]

**Comment by zyrouge** [comment]
Fixed in v0.0.29-beta.0.
