### ISSUE TITLE
[Feature] Auto Tracking using MAL-Sync

### ISSUE THREAD

**Issue by saipraveenbammidi** [zyrouge/yukino-app#9]
**Is your feature request related to a problem? Please describe.**
It would be good if it had auto tracking feature by using any extension like mal-sync.

**Describe the solution you'd like**
For the feature I requested I would like to suggest a project named Mal-sync

**Describe alternatives you've considered**
As far as I know there is no better alt for this,

**Additional context**
Simply Mal-sync is a thing which Integrates MyAnimeList/AniList/Kitsu/Simkl into various sites, with auto episode tracking(this is the feature that to be implemented, auto tracking).
https://github.com/MALSync/MALSync#readme

**Comment by zyrouge** [comment]
Certainly I am not sure how this is gonna get implemented as the app itself is not a hosted website rather a local static site ran inside a secure browser environment. Might need help on this being implemented.

**Comment by zyrouge** [comment]
MAL Sync cannot be added to mobile platform as they don't support extensions by any means. Closing this in favor of custom implementation.
